#!/bin/bash

# toggles the external monitor on/off in specified direction
IN="LVDS1"
EXT1="VGA1"
EXT2="DP1"

function connected {
  xrandr | grep "$1 connected"
}

function disconnected {
  xrandr | grep "$1 disconnected"
}

if (connected $IN && connected $EXT1 && connected $EXT2); then
    ~/.screenlayout/pre-ext.sh
    ~/.screenlayout/ext-all.sh
elif (connected $IN && connected $EXT1 && disconnected $EXT2); then
    ~/.screenlayout/pre-ext.sh
    ~/.screenlayout/ext-${EXT1}.sh
elif (connected $IN && disconnected $EXT1 && connected $EXT2); then
    ~/.screenlayout/pre-ext.sh
    ~/.screenlayout/ext-${EXT2}.sh
else
    ~/.screenlayout/laptop-only.sh
fi

pkill -f nm-applet

nohup nm-applet 2>&1 >/dev/null &

